### ISSUE TITLE
4B music blocks do not switch on and off

### ISSUE THREAD

**Issue by bobthekingofegypt** [max4805/IntoTheJungleIssues#14]
Playing 4B, on the last room with the music blocks I get a single sound and then the note blocks never turn on and off again.

The console is filled with messages saying
```
(08/22/2021 19:53:13) [Everest] [Verbose] [Audio] Event not found: event:/JungleMusicByTg90/cassette/ch4
```

I've tried updating everything to the latest versions with Everest but no luck.

**Comment by max4805** [comment]
Please try again on the latest version of Everest that just came out (3013), there were some audio loading issues on 3008.

**Comment by bobthekingofegypt** [comment]
Works perfectly with 3013.  Thanks for the help and the levels, they were great.
